
# About the project

*Write a short description about the course and add a link to your GitHub repository here. This is an R Markdown (.Rmd) file so you can use R Markdown syntax.*

<<<<<<< HEAD

=======
>>>>>>> 29edd461f5a9720abe87d8892882ba8df3ef73eb
I am feeling excited!

Here is the link for my github

https://github.com/vinnu0143/IODS-project

And here is the link to the diary page:
<<<<<<< HEAD

https://vinnu0143.github.io/IODS-project/

I expect to learn about the Open science, sharing the data using Github and learn some programming using R which will make my life easier for doing some statistics im my research work

I heard about this course from yammer group

=======
https://vinnu0143.github.io/IODS-project/

I expect to learn about open science, sharing the data using Github and learn some programming using R which will make my life easier for doing some statistics in my research work.

I heard about this course from yammer group
>>>>>>> 29edd461f5a9720abe87d8892882ba8df3ef73eb
